# Advanced numpy Operations (30 mins)


## Agenda

1. **Array Broadcasting**
   - Understanding broadcasting rules
   - Practical examples
   
2. **Array reshaping and transposing**
   - Reshaping arrays
   - Transposing arrays
   
3. **Matrix multiplication and linear algebra**
   - Dot product
   - Matrix multiplication
   - Eigenvalues and Eigenvectors
   
4. **Exercise: Matrix Operations**
   - Tasks to practice the above concepts
   
5. **Graded Problem (5 minutes)**



## Array Broadcasting

In numpy, broadcasting allows us to perform binary operations on arrays of different shapes and sizes. 
Broadcasting automates certain operations to match the shapes, making it easier to perform array manipulations.

### Understanding broadcasting rules

Broadcasting follows a certain set of rules to determine the interaction between two arrays:

1. If the arrays have different dimensions, prepend the shape of the lower dimensional array with 1s.
2. The sizes of the dimensions are considered compatible when they are equal or one of them is 1.
3. The arrays can be broadcasted together if their dimensions are compatible.

Let's look at some practical examples.


In [1]:
import numpy as np
# Two arrays of different dimensions
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# Broadcasting allows these arrays to be added together
result = a + b
print("Result of broadcasting:")
print(result)


Result of broadcasting:
[[11 12 13]
 [21 22 23]
 [31 32 33]]



## Array reshaping and transposing

### Reshaping arrays
Numpy provides various ways to change the shape of existing arrays without changing their data.

### Transposing arrays
Transposing is a special form of reshaping that returns a new array with the number of rows and columns switched.

Let's look at some examples.


In [2]:

# Reshaping a 1D array into a 2D array (of different shapes)
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print("Reshaped array:")
print(reshaped_arr)

# Transposing a 2D array
transposed_arr = reshaped_arr.T
print("\nTransposed array:")
print(transposed_arr)


Reshaped array:
[[1 2 3]
 [4 5 6]]

Transposed array:
[[1 4]
 [2 5]
 [3 6]]



## Matrix multiplication and linear algebra

### Dot Product
The dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers and returns a single number.

### Matrix Multiplication
In numpy, the `dot` function also performs matrix multiplication when applied on 2D arrays.

### Eigenvalues and Eigenvectors
Eigenvalues and eigenvectors are important in a variety of scientific computing problems.

Let's explore these with examples.


In [3]:

# Dot Product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.dot(A, B)
print("\nMatrix Multiplication:")
print(matrix_multiplication)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Dot Product: 32

Matrix Multiplication:
[[19 22]
 [43 50]]

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



## Exercise: Matrix Operations

1. Create a 2x2 matrix and multiply it by itself.
2. Create a 3x3 identity matrix.
3. Find the eigenvalues and eigenvectors of a 2x2 matrix.

Perform these tasks to get hands-on experience with matrix operations.



## Answers to Exercises

1. Create a 2x2 matrix and multiply it by itself.
   ```python
   matrix = np.array([[1, 2], [3, 4]])
   np.dot(matrix, matrix)
   ```
   
2. Create a 3x3 identity matrix.
   ```python
   np.identity(3)
   ```
   
3. Find the eigenvalues and eigenvectors of a 2x2 matrix.
   ```python
   matrix = np.array([[1, 2], [3, 4]])
   np.linalg.eig(matrix)
   ```



## Graded Problem (5 minutes)

Given two matrices \( A = \left[egin{array}{cc} 1 & 2 \ 3 & 4 \end{array}
ight] \) 
and \( B = \left[egin{array}{cc} 5 & 6 \ 7 & 8 \end{array}
ight] \), perform the following tasks:

1. Multiply matrix \( A \) by matrix \( B \).
2. Find the eigenvalues and eigenvectors of matrix \( A \).
3. Calculate the dot product of the first row of matrix \( A \) and the second row of matrix \( B \).

Submit your answers along with the code used to obtain them. This problem will be graded.
