# Numpy Array Manipulations (30 mins)


## Agenda

1. **Array Reshaping and Transposition**
    - Reshaping
    - Transposing
   
2. **Array Splitting and Combining**
    - Splitting
    - Combining
   
3. **Advanced Indexing and Slicing**
    - Boolean indexing
    - Fancy indexing
   
4. **Exercise: Array Manipulations**
    - Tasks to practice array manipulations in NumPy
   
5. **Graded Problem (5 minutes)**



## 1. Array Reshaping and Transposition

NumPy provides several ways to rearrange and modify the structure of arrays.

### Reshaping

Changing the shape of an array without altering the data within.

### Transposing

Flipping the axes of an array.

Let's dive into some examples.


In [1]:

import numpy as np

# Reshaping an array
arr = np.arange(1, 10)
reshaped_arr = arr.reshape(3, 3)
print('Original Array:', arr)
print('Reshaped Array:\n', reshaped_arr)

# Transposing an array
transposed_arr = reshaped_arr.T
print('Transposed Array:\n', transposed_arr)


Original Array: [1 2 3 4 5 6 7 8 9]
Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]



## 2. Array Splitting and Combining

### Splitting

Breaking one array into multiple smaller arrays.

### Combining

Merging multiple arrays into one larger array.

Let's see these operations in action.


In [2]:

# Splitting an array
split_arr1, split_arr2, split_arr3 = np.split(arr, [2, 5])
print('Original Array:', arr)
print('Split arrays:', split_arr1, split_arr2, split_arr3)

# Combining arrays
combined_arr = np.concatenate([split_arr1, split_arr2, split_arr3])
print('Combined Array:', combined_arr)


Original Array: [1 2 3 4 5 6 7 8 9]
Split arrays: [1 2] [3 4 5] [6 7 8 9]
Combined Array: [1 2 3 4 5 6 7 8 9]



## 3. Advanced Indexing and Slicing

NumPy offers more sophisticated ways to index and slice arrays.

### Boolean Indexing

Indexing using boolean conditions.

### Fancy Indexing

Indexing using integer arrays.

Let's check out some examples.


In [3]:

# Boolean Indexing
arr = np.random.randint(1, 10, size=10)
print('Original Array:', arr)
print('Values greater than 5:', arr[arr > 5])

# Fancy Indexing
indices = [1, 3, 5]
print('Values at selected indices:', arr[indices])


Original Array: [6 6 8 3 6 6 8 1 5 9]
Values greater than 5: [6 6 8 6 6 8 9]
Values at selected indices: [6 3 6]



## 4. Exercise: Array Manipulations

1. Create a 3x3 matrix and transpose it.
2. Create two arrays of shape (3, 3) and concatenate them vertically.

Try to complete these exercises for hands-on practice.



## Exercise Answers

1. **Create a 3x3 matrix and transpose it.**
    ```python
    matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    transposed_matrix = matrix.T
    print('Transposed Matrix:\n', transposed_matrix)
    ```

2. **Create two arrays of shape (3, 3) and concatenate them vertically.**
    ```python
    arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
    concatenated_arr = np.vstack([arr1, arr2])
    print('Concatenated Array:\n', concatenated_arr)
    ```



## 5. Graded Problem (5 minutes)

Create a 5x5 NumPy array with random integers. Then:

1. Extract the diagonal elements and put them in a 1D array.
2. Replace all the values above the diagonal with zeros.

Submit your solution for grading.
